


development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: google-notes
  pool: 5
  username: brainx
  password: brainx321
 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: google-notes
  pool: 5
  username: brainx
  password: brainx321


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: google-notes
  pool: 5
  username: brainx
  password: brainx321

