default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  database: google-notes
  username: brainx
  password: brainx321
 
test:
  <<: *default
  database: google-notes-test
  username: brainx
  password: brainx321

production:
  <<: *default
  database: google-notes-prod
  username: brainx
  password: brainx321

