default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: brainx
  password: brainx321

development:
  <<: *default
  database: google-notes

test:
  <<: *default
  database: google-notes-test

production:
  <<: *default
  database: google-notes-prod
  username: brainx
  password: brainx321

